name: mode
description: A new Flutter project.
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  get_it: ^7.1.4

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
flutter:
  uses-material-design: true