name: mode
description: A new Flutter project.
publish_to: 'none' 

version: 0.1.0

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  get_it: ^7.1.3
  flutter_svg: ^0.22.0
  easy_localization: ^3.0.0
  cached_network_image: ^3.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
flutter:
  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Regular.ttf
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Bold.ttf
          weight: 700
        - asset: assets/fonts/ChakraPetch/ChakraPetch-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Light.ttf
          weight: 400
        - asset: assets/fonts/ChakraPetch/ChakraPetch-Italic.ttf
          style: italic

  uses-material-design: true